export const food = [
  {
    id: 0,
    img: "./images/A dish from Warehouse London.jpg",
    name: "A dish from Warehouse London",
    price: "8.00",
    category: "lunch",
  },
  {
    id: 1,
    img: "./images/Blue & Green Matcha Lattes.jpg",
    name: "Blue & Green Matcha Lattes",
    price: "6.00",
    category: "drinks",
  },
  {
    id: 2,
    img: "./images/burger-with-vegetable.jpg",
    name: "burger with vegetable",
    price: "7.00",
    category: "lunch",
  },
  {
    id: 3,
    img: "./images/fried chicken.jpg",
    name: "fried chicken",
    price: "12.00",
    category: "dinner",
  },
  {
    id: 4,
    img: "./images/juicy lemon drink.jpg",
    name: "juicy lemon drink",
    price: "5.00",
    category: "drinks",
  },
  {
    id: 5,
    img: "./images/Lasagna Food.jpg",
    name: "Lasagna Food",
    price: "14.00",
    category: "dinner",
  },
  {
    id: 6,
    img: "./images/Methi (Fenugreek) Vada - Indian Cuisine.jpg",
    name: "Methi (Fenugreek) Vada",
    price: "7.00",
    category: "lunch",
  },
  {
    id: 7,
    img: "./images/Pav bhaji.jpg",
    name: "Pav bhaji",
    price: "10.00",
    category: "dinner",
  },
  {
    id: 8,
    img: "./images/Poori Indian snack.jpg",
    name: "Poori Indian snack",
    price: "7.00",
    category: "lunch",
  },
  {
    id: 9,
    img: "./images/ramen-seafood-noodles.jpg",
    name: "ramen seafood noodles",
    price: "10.00",
    category: "dinner",
  },
  {
    id: 10,
    img: "./images/Strawberry cocktail drinks.jpg",
    name: "Strawberry cocktail drinks",
    price: "6.00",
    category: "drinks",
  },
  {
    id: 11,
    img: "./images/strawbey cocktail.jpg",
    name: "strawbey cocktail",
    price: "6.00",
    category: "drinks",
  },
];
